name : getman
services:
  db: 
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Amaanasp
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"